export type HelpCategory = 'getting-started' | 'portfolio' | 'trading' | 'analytics' | 'compliance' | 'esg' | 'documents' | 'troubleshooting'

export interface FAQ {
  id: string
  category: HelpCategory
  question: string
  answer: string
  keywords: string[]
  relatedVideos?: string[]
  relatedFAQs?: string[]
}

export interface VideoTutorial {
  id: string
  title: string
  description: string
  category: HelpCategory
  duration: string
  thumbnail: string
  videoUrl: string
  transcript?: string
  relatedFAQs?: string[]
}

export const helpCategories = [
  { id: 'getting-started' as HelpCategory, label: 'Getting Started', icon: 'rocket' },
  { id: 'portfolio' as HelpCategory, label: 'Portfolio Management', icon: 'folder' },
  { id: 'trading' as HelpCategory, label: 'Loan Trading', icon: 'handshake' },
  { id: 'analytics' as HelpCategory, label: 'Analytics & Reports', icon: 'chart' },
  { id: 'compliance' as HelpCategory, label: 'Compliance & LMA', icon: 'shield' },
  { id: 'esg' as HelpCategory, label: 'ESG & Green Lending', icon: 'leaf' },
  { id: 'documents' as HelpCategory, label: 'Document Analysis', icon: 'file' },
  { id: 'troubleshooting' as HelpCategory, label: 'Troubleshooting', icon: 'wrench' },
]

export const faqs: FAQ[] = [
  {
    id: 'faq-1',
    category: 'getting-started',
    question: 'How do I upload my first loan document?',
    answer: 'Click the "Upload Document" button in the top right corner of the dashboard. You can upload PDF, DOCX, or TXT files. Our AI will automatically extract key information including borrower details, loan amounts, interest rates, covenants, and risk factors. The process typically takes 15-30 seconds.',
    keywords: ['upload', 'document', 'first', 'start', 'begin', 'pdf', 'file'],
    relatedVideos: ['video-1'],
    relatedFAQs: ['faq-2', 'faq-15'],
  },
  {
    id: 'faq-2',
    category: 'getting-started',
    question: 'What file formats are supported for document upload?',
    answer: 'LoanFlow AI supports PDF (.pdf), Microsoft Word (.docx), and plain text (.txt) formats. We recommend using PDF files for best extraction accuracy. Documents can be up to 10MB in size.',
    keywords: ['format', 'file', 'pdf', 'docx', 'txt', 'supported', 'type'],
    relatedFAQs: ['faq-1'],
  },
  {
    id: 'faq-3',
    category: 'getting-started',
    question: 'Can I try the platform with sample data?',
    answer: 'Yes! Click the "Load Demo Data" button on the welcome screen or in the header. This will populate your portfolio with realistic sample loans across various industries, risk levels, and currencies. Perfect for exploring all features before uploading your own documents.',
    keywords: ['demo', 'sample', 'test', 'try', 'example', 'data'],
    relatedVideos: ['video-1'],
  },
  {
    id: 'faq-4',
    category: 'portfolio',
    question: 'How do I filter loans in my portfolio?',
    answer: 'Use the filter controls above the loan list to narrow down your view. You can filter by status (active, pending, defaulted, paid-off), risk level (low, medium, high, critical), currency (USD, EUR, GBP, etc.), and industry. Combine multiple filters and use the search bar to find specific borrowers.',
    keywords: ['filter', 'search', 'portfolio', 'find', 'status', 'risk', 'currency'],
    relatedVideos: ['video-2'],
    relatedFAQs: ['faq-5'],
  },
  {
    id: 'faq-5',
    category: 'portfolio',
    question: 'What do the portfolio metrics mean?',
    answer: 'Total Exposure shows your aggregate loan value across all currencies (converted to USD). Avg Risk Score is calculated from individual loan risk assessments (1-10 scale). Covenant Compliance shows the percentage of covenants being met. High Risk Alerts count loans with risk scores above 7.',
    keywords: ['metrics', 'exposure', 'risk', 'covenant', 'kpi', 'dashboard'],
    relatedVideos: ['video-2'],
  },
  {
    id: 'faq-6',
    category: 'trading',
    question: 'How do I list a loan for trading?',
    answer: 'Open any loan detail page and click "Create Listing" in the Trading section. Set your asking price and minimum bid amount. Your listing will be visible to other market participants. You can track views and incoming bids in real-time from the Trading Hub.',
    keywords: ['trading', 'list', 'sell', 'marketplace', 'bid', 'price'],
    relatedVideos: ['video-3'],
    relatedFAQs: ['faq-7', 'faq-8'],
  },
  {
    id: 'faq-7',
    category: 'trading',
    question: 'How does the bidding process work?',
    answer: 'Once a loan is listed, interested buyers can place bids above the minimum bid amount. Sellers receive notifications of new bids and can accept, reject, or counter. The platform shows market intelligence including price discovery data and similar loan comparisons to help both parties.',
    keywords: ['bid', 'bidding', 'offer', 'buy', 'trading', 'price'],
    relatedVideos: ['video-3'],
    relatedFAQs: ['faq-6'],
  },
  {
    id: 'faq-8',
    category: 'trading',
    question: 'What is the market intelligence feature?',
    answer: 'Market Intelligence uses AI to analyze trading patterns, price trends, and comparable loan transactions. It provides price recommendations, identifies arbitrage opportunities, and shows supply/demand dynamics. This helps you make data-driven trading decisions.',
    keywords: ['market', 'intelligence', 'ai', 'price', 'trends', 'analysis'],
    relatedVideos: ['video-4'],
  },
  {
    id: 'faq-9',
    category: 'analytics',
    question: 'What insights does the Analytics Dashboard provide?',
    answer: 'The Analytics Dashboard offers portfolio concentration analysis, risk distribution charts, performance trends over time, covenant compliance tracking, and predictive default probability models. All visualizations are interactive and can be exported for reporting.',
    keywords: ['analytics', 'dashboard', 'insights', 'reports', 'visualization', 'charts'],
    relatedVideos: ['video-4'],
    relatedFAQs: ['faq-10'],
  },
  {
    id: 'faq-10',
    category: 'analytics',
    question: 'How accurate are the predictive analytics?',
    answer: 'Our AI models are trained on historical loan performance data and market conditions. Default probability predictions have shown 85%+ accuracy in backtesting. Models consider credit factors, market conditions, covenant status, and macroeconomic indicators. Always use as one input in your decision-making process.',
    keywords: ['predictive', 'accuracy', 'ai', 'model', 'default', 'probability'],
    relatedFAQs: ['faq-9'],
  },
  {
    id: 'faq-11',
    category: 'compliance',
    question: 'What is LMA compliance scoring?',
    answer: 'LMA (Loan Market Association) compliance scoring assesses how well your loan documentation adheres to LMA standard terms and definitions. Scores range from 0-100, with gaps identified by section. This helps ensure market standardization and easier loan trading.',
    keywords: ['lma', 'compliance', 'score', 'standard', 'gap', 'documentation'],
    relatedVideos: ['video-5'],
    relatedFAQs: ['faq-12'],
  },
  {
    id: 'faq-12',
    category: 'compliance',
    question: 'How do I fix compliance gaps?',
    answer: 'The Compliance Checker details each gap with severity level (high, medium, low) and specific recommendations. Click on any gap to see suggested language and LMA standard references. You can export a gap analysis report to share with legal teams.',
    keywords: ['compliance', 'gap', 'fix', 'resolve', 'recommendation'],
    relatedVideos: ['video-5'],
    relatedFAQs: ['faq-11'],
  },
  {
    id: 'faq-13',
    category: 'esg',
    question: 'How are ESG scores calculated?',
    answer: 'ESG scores analyze Environmental, Social, and Governance factors from loan documents and borrower data. Scores range from A (excellent) to F (poor). We evaluate carbon footprint commitments, social impact initiatives, board diversity, and governance structures. Scores align with industry frameworks like TCFD and SASB.',
    keywords: ['esg', 'score', 'environmental', 'social', 'governance', 'green'],
    relatedVideos: ['video-6'],
    relatedFAQs: ['faq-14'],
  },
  {
    id: 'faq-14',
    category: 'esg',
    question: 'What qualifies as a green loan?',
    answer: 'Green loans are designated for environmentally beneficial projects like renewable energy, energy efficiency, clean transportation, or sustainable water management. We identify green loans based on use of proceeds, Green Loan Principles compliance, and environmental impact metrics.',
    keywords: ['green', 'loan', 'environmental', 'sustainable', 'renewable'],
    relatedVideos: ['video-6'],
    relatedFAQs: ['faq-13'],
  },
  {
    id: 'faq-15',
    category: 'documents',
    question: 'What information does the AI extract from documents?',
    answer: 'Our AI extracts borrower details, loan amount and currency, interest rates, maturity dates, covenants with thresholds, risk factors, collateral information, ESG commitments, and LMA standard clause compliance. Extraction typically achieves 95%+ accuracy on standard loan documents.',
    keywords: ['extract', 'ai', 'document', 'analysis', 'ocr', 'parse'],
    relatedVideos: ['video-1'],
    relatedFAQs: ['faq-1', 'faq-16'],
  },
  {
    id: 'faq-16',
    category: 'documents',
    question: 'Can I upload multiple documents at once?',
    answer: 'Yes! Use the "Batch Upload" feature to upload up to 50 documents simultaneously. The AI will process them in parallel and add all loans to your portfolio. This is ideal for onboarding existing portfolios or processing large syndication deals.',
    keywords: ['batch', 'multiple', 'bulk', 'upload', 'many'],
    relatedFAQs: ['faq-15'],
  },
  {
    id: 'faq-17',
    category: 'documents',
    question: 'How do I export my portfolio data?',
    answer: 'Click the "Export" button in the header. Choose from CSV (spreadsheet format), JSON (developer format), or PDF (formatted report). You can export the entire portfolio or filtered subsets. Exports include all loan details, analytics, and compliance scores.',
    keywords: ['export', 'download', 'csv', 'json', 'pdf', 'report'],
    relatedFAQs: ['faq-5'],
  },
  {
    id: 'faq-18',
    category: 'troubleshooting',
    question: 'Why is my document taking a long time to process?',
    answer: 'Large or complex documents may take up to 2 minutes to process. Scanned documents (images) take longer than text-based PDFs. If processing exceeds 3 minutes, try re-uploading. Ensure your file is under 10MB and is a supported format.',
    keywords: ['slow', 'processing', 'time', 'wait', 'stuck', 'loading'],
    relatedFAQs: ['faq-2', 'faq-15'],
  },
  {
    id: 'faq-19',
    category: 'troubleshooting',
    question: 'What if the AI extracts incorrect information?',
    answer: 'You can manually edit any loan details by clicking the edit icon in the loan detail view. We continuously improve our models based on feedback. If you notice systematic errors, please report them through the feedback form so we can retrain the model.',
    keywords: ['wrong', 'incorrect', 'error', 'fix', 'edit', 'accuracy'],
    relatedFAQs: ['faq-15'],
  },
  {
    id: 'faq-20',
    category: 'troubleshooting',
    question: 'How do I delete a loan from my portfolio?',
    answer: 'Open the loan detail page and click the "Delete" button in the actions menu. This permanently removes the loan and all associated data. For compliance reasons, you may want to export the data before deletion.',
    keywords: ['delete', 'remove', 'clear', 'erase'],
    relatedFAQs: ['faq-17'],
  },
  {
    id: 'faq-21',
    category: 'analytics',
    question: 'What is stress testing and how does it work?',
    answer: 'Stress testing simulates how your portfolio would perform under adverse scenarios like interest rate shocks, recession, or credit downgrades. Run predefined scenarios or create custom ones with specific parameter changes. Results show potential losses, covenant breaches, and at-risk loans.',
    keywords: ['stress', 'test', 'scenario', 'simulation', 'risk', 'adverse'],
    relatedVideos: ['video-4'],
  },
  {
    id: 'faq-22',
    category: 'portfolio',
    question: 'What are covenants and why do they matter?',
    answer: 'Covenants are financial or operational conditions borrowers must maintain (e.g., debt-to-equity ratios, minimum cash balances). Breaches can trigger defaults or renegotiation. LoanFlow AI monitors all covenants and alerts you when values approach thresholds.',
    keywords: ['covenant', 'breach', 'threshold', 'condition', 'trigger'],
    relatedFAQs: ['faq-5'],
  },
  {
    id: 'faq-23',
    category: 'trading',
    question: 'Is my trading data private?',
    answer: 'In this demo, all trading is simulated within your session. In a production environment, you would control visibility settings for each listing (private consortium, public marketplace, or direct offers). All data transmission would be encrypted end-to-end.',
    keywords: ['privacy', 'security', 'confidential', 'data', 'protection'],
  },
  {
    id: 'faq-24',
    category: 'getting-started',
    question: 'Can I access the tutorial again after my first visit?',
    answer: 'Yes! Click the "Tutorial" button with the sparkle icon in the header at any time to restart the interactive walkthrough. The tutorial covers all major features and takes about 3 minutes to complete.',
    keywords: ['tutorial', 'guide', 'walkthrough', 'help', 'learn'],
    relatedVideos: ['video-1'],
  },
]

export const videoTutorials: VideoTutorial[] = [
  {
    id: 'video-1',
    title: 'Getting Started with LoanFlow AI',
    description: 'Learn how to upload your first loan document, navigate the dashboard, and explore key features. Perfect for new users.',
    category: 'getting-started',
    duration: '3:24',
    thumbnail: 'https://placehold.co/640x360/4f46e5/ffffff?text=Getting+Started',
    videoUrl: '#',
    transcript: 'Welcome to LoanFlow AI. In this tutorial, we will walk you through uploading your first loan document...',
    relatedFAQs: ['faq-1', 'faq-2', 'faq-3'],
  },
  {
    id: 'video-2',
    title: 'Managing Your Loan Portfolio',
    description: 'Master portfolio filtering, understand key metrics, and learn how to monitor risk across your entire loan book.',
    category: 'portfolio',
    duration: '5:12',
    thumbnail: 'https://placehold.co/640x360/0891b2/ffffff?text=Portfolio+Management',
    videoUrl: '#',
    transcript: 'Your portfolio dashboard gives you a comprehensive view of all your loans...',
    relatedFAQs: ['faq-4', 'faq-5', 'faq-22'],
  },
  {
    id: 'video-3',
    title: 'Trading Loans on the Platform',
    description: 'Discover how to list loans for sale, place bids, and use market intelligence to optimize pricing and find opportunities.',
    category: 'trading',
    duration: '6:45',
    thumbnail: 'https://placehold.co/640x360/059669/ffffff?text=Loan+Trading',
    videoUrl: '#',
    transcript: 'The Trading Hub enables transparent secondary market transactions...',
    relatedFAQs: ['faq-6', 'faq-7', 'faq-8'],
  },
  {
    id: 'video-4',
    title: 'Advanced Analytics and Stress Testing',
    description: 'Explore predictive analytics, run stress tests, and generate comprehensive portfolio reports with actionable insights.',
    category: 'analytics',
    duration: '7:18',
    thumbnail: 'https://placehold.co/640x360/dc2626/ffffff?text=Analytics+%26+Stress+Tests',
    videoUrl: '#',
    transcript: 'Analytics Dashboard provides deep insights into portfolio performance and risks...',
    relatedFAQs: ['faq-9', 'faq-10', 'faq-21'],
  },
  {
    id: 'video-5',
    title: 'LMA Compliance and Documentation Standards',
    description: 'Understand LMA compliance scoring, identify documentation gaps, and align your loan agreements with market standards.',
    category: 'compliance',
    duration: '4:55',
    thumbnail: 'https://placehold.co/640x360/7c3aed/ffffff?text=LMA+Compliance',
    videoUrl: '#',
    transcript: 'The Loan Market Association sets standards for loan documentation...',
    relatedFAQs: ['faq-11', 'faq-12'],
  },
  {
    id: 'video-6',
    title: 'ESG Scoring and Green Lending',
    description: 'Learn how ESG scores are calculated, track sustainability metrics, and identify green lending opportunities in your portfolio.',
    category: 'esg',
    duration: '5:30',
    thumbnail: 'https://placehold.co/640x360/16a34a/ffffff?text=ESG+%26+Green+Lending',
    videoUrl: '#',
    transcript: 'Environmental, Social, and Governance factors are increasingly important in lending...',
    relatedFAQs: ['faq-13', 'faq-14'],
  },
  {
    id: 'video-7',
    title: 'Batch Document Upload and Processing',
    description: 'Efficiently onboard large portfolios using batch upload. Process up to 50 documents simultaneously with AI extraction.',
    category: 'documents',
    duration: '3:42',
    thumbnail: 'https://placehold.co/640x360/ea580c/ffffff?text=Batch+Upload',
    videoUrl: '#',
    transcript: 'When you have multiple loan documents to upload, the batch feature saves time...',
    relatedFAQs: ['faq-16', 'faq-15'],
  },
  {
    id: 'video-8',
    title: 'Exporting and Reporting',
    description: 'Generate professional reports and export your portfolio data in multiple formats for compliance, audits, or analysis.',
    category: 'portfolio',
    duration: '2:58',
    thumbnail: 'https://placehold.co/640x360/0891b2/ffffff?text=Export+%26+Reports',
    videoUrl: '#',
    transcript: 'LoanFlow AI offers flexible export options for your portfolio data...',
    relatedFAQs: ['faq-17'],
  },
]
