import { TeamMember, AlertRoute } from './teamTypes'

export const sampleTeamMembers: TeamMember[] = [
  {
    id: 'TM-001',
    name: 'Sarah Chen',
    email: 'sarah.chen@loanflow.ai',
    role: 'portfolio_manager',
    department: 'Portfolio Management',
    status: 'active',
    specializations: ['Technology', 'Healthcare', 'Real Estate'],
    maxLoans: 30,
    currentLoans: 18,
    alertPreferences: {
      autoAssign: true,
      maxAlertsPerDay: 75,
      preferredAlertTypes: ['covenant_breach', 'high_risk_loan', 'default_probability_high'],
    },
    workloadStatus: 'medium',
    performanceMetrics: {
      avgResponseTime: 45,
      alertsResolved: 234,
      loansManaged: 89,
      accuracyScore: 96,
    },
    availability: {
      timezone: 'America/New_York',
      workingHours: {
        start: '08:00',
        end: '18:00',
      },
      daysOff: [],
    },
  },
  {
    id: 'TM-002',
    name: 'Marcus Rodriguez',
    email: 'marcus.rodriguez@loanflow.ai',
    role: 'risk_analyst',
    department: 'Risk Management',
    status: 'active',
    specializations: ['Credit Risk', 'Market Risk', 'ESG Analysis'],
    maxLoans: 25,
    currentLoans: 22,
    alertPreferences: {
      autoAssign: true,
      maxAlertsPerDay: 60,
      preferredAlertTypes: ['critical_risk_loan', 'covenant_at_risk', 'default_probability_high'],
    },
    workloadStatus: 'high',
    performanceMetrics: {
      avgResponseTime: 32,
      alertsResolved: 412,
      loansManaged: 156,
      accuracyScore: 98,
    },
    availability: {
      timezone: 'America/Chicago',
      workingHours: {
        start: '07:00',
        end: '16:00',
      },
      daysOff: [],
    },
  },
  {
    id: 'TM-003',
    name: 'Emily Watson',
    email: 'emily.watson@loanflow.ai',
    role: 'compliance_officer',
    department: 'Compliance',
    status: 'active',
    specializations: ['LMA Standards', 'Regulatory Compliance', 'Documentation'],
    maxLoans: 40,
    currentLoans: 15,
    alertPreferences: {
      autoAssign: true,
      maxAlertsPerDay: 50,
      preferredAlertTypes: ['lma_compliance_gap', 'covenant_breach'],
    },
    workloadStatus: 'low',
    performanceMetrics: {
      avgResponseTime: 28,
      alertsResolved: 189,
      loansManaged: 67,
      accuracyScore: 99,
    },
    availability: {
      timezone: 'Europe/London',
      workingHours: {
        start: '09:00',
        end: '17:30',
      },
      daysOff: [],
    },
  },
  {
    id: 'TM-004',
    name: 'David Kim',
    email: 'david.kim@loanflow.ai',
    role: 'trader',
    department: 'Trading',
    status: 'active',
    specializations: ['Secondary Market', 'Pricing', 'Syndication'],
    maxLoans: 20,
    currentLoans: 12,
    alertPreferences: {
      autoAssign: false,
      maxAlertsPerDay: 40,
      preferredAlertTypes: ['maturity_approaching'],
    },
    workloadStatus: 'medium',
    performanceMetrics: {
      avgResponseTime: 65,
      alertsResolved: 87,
      loansManaged: 43,
      accuracyScore: 94,
    },
    availability: {
      timezone: 'Asia/Singapore',
      workingHours: {
        start: '08:30',
        end: '17:30',
      },
      daysOff: [],
    },
  },
  {
    id: 'TM-005',
    name: 'Jennifer Park',
    email: 'jennifer.park@loanflow.ai',
    role: 'analyst',
    department: 'Credit Analysis',
    status: 'active',
    specializations: ['Financial Analysis', 'Industry Research', 'Covenant Analysis'],
    maxLoans: 15,
    currentLoans: 8,
    alertPreferences: {
      autoAssign: true,
      maxAlertsPerDay: 30,
      preferredAlertTypes: ['covenant_at_risk', 'esg_score_downgrade'],
    },
    workloadStatus: 'low',
    performanceMetrics: {
      avgResponseTime: 52,
      alertsResolved: 124,
      loansManaged: 34,
      accuracyScore: 92,
    },
    availability: {
      timezone: 'America/Los_Angeles',
      workingHours: {
        start: '09:00',
        end: '17:00',
      },
      daysOff: [],
    },
  },
  {
    id: 'TM-006',
    name: 'Ahmed Hassan',
    email: 'ahmed.hassan@loanflow.ai',
    role: 'risk_analyst',
    department: 'Risk Management',
    status: 'active',
    specializations: ['Emerging Markets', 'ESG', 'Stress Testing'],
    maxLoans: 25,
    currentLoans: 10,
    alertPreferences: {
      autoAssign: true,
      maxAlertsPerDay: 55,
      preferredAlertTypes: ['esg_score_downgrade', 'high_risk_loan'],
    },
    workloadStatus: 'low',
    performanceMetrics: {
      avgResponseTime: 38,
      alertsResolved: 167,
      loansManaged: 52,
      accuracyScore: 95,
    },
    availability: {
      timezone: 'Europe/Paris',
      workingHours: {
        start: '08:00',
        end: '17:00',
      },
      daysOff: [],
    },
  },
]

export const sampleAlertRoutes: AlertRoute[] = [
  {
    id: 'ROUTE-001',
    name: 'Critical Risk Alerts',
    description: 'Route critical risk and covenant breach alerts to senior risk analysts',
    priority: 1,
    conditions: {
      alertTypes: ['critical_risk_loan', 'covenant_breach'],
      severities: ['critical'],
      loanCriteria: {
        minAmount: 5000000,
      },
    },
    routing: {
      type: 'workload_based',
      assignTo: ['TM-002', 'TM-006'],
      escalationEnabled: true,
      escalationTime: 30,
      escalateTo: ['TM-001'],
      notifyAll: false,
    },
    enabled: true,
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'ROUTE-002',
    name: 'Compliance Gaps',
    description: 'Route LMA compliance issues to compliance team',
    priority: 2,
    conditions: {
      alertTypes: ['lma_compliance_gap'],
      severities: ['high', 'medium'],
    },
    routing: {
      type: 'skill_based',
      assignTo: ['TM-003'],
      escalationEnabled: true,
      escalationTime: 60,
      escalateTo: ['TM-001'],
      notifyAll: false,
    },
    enabled: true,
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'ROUTE-003',
    name: 'ESG Monitoring',
    description: 'Route ESG-related alerts to ESG specialists',
    priority: 3,
    conditions: {
      alertTypes: ['esg_score_downgrade'],
      severities: ['high', 'medium', 'low'],
    },
    routing: {
      type: 'skill_based',
      assignTo: ['TM-002', 'TM-006'],
      escalationEnabled: false,
      notifyAll: false,
    },
    enabled: true,
    createdAt: new Date('2024-01-16').toISOString(),
    updatedAt: new Date('2024-01-16').toISOString(),
  },
  {
    id: 'ROUTE-004',
    name: 'Technology Sector Loans',
    description: 'Route technology sector loan alerts to specialists',
    priority: 4,
    conditions: {
      alertTypes: ['covenant_at_risk', 'high_risk_loan', 'default_probability_high'],
      severities: ['high', 'medium'],
      loanCriteria: {
        industries: ['Technology', 'Software'],
      },
    },
    routing: {
      type: 'skill_based',
      assignTo: ['TM-001'],
      escalationEnabled: true,
      escalationTime: 45,
      escalateTo: ['TM-002'],
      notifyAll: false,
    },
    enabled: true,
    createdAt: new Date('2024-01-17').toISOString(),
    updatedAt: new Date('2024-01-17').toISOString(),
  },
  {
    id: 'ROUTE-005',
    name: 'General Portfolio Alerts',
    description: 'Default routing for all other alerts using round-robin',
    priority: 99,
    conditions: {
      alertTypes: [
        'covenant_at_risk',
        'high_risk_loan',
        'default_probability_high',
        'maturity_approaching',
      ],
      severities: ['high', 'medium', 'low'],
    },
    routing: {
      type: 'round_robin',
      assignTo: ['TM-001', 'TM-005'],
      escalationEnabled: false,
      notifyAll: false,
    },
    enabled: true,
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
]
