import { Loan } from './types'

export const sampleLoans: Loan[] = [
  {
    id: 'LOAN-2024-001',
    borrowerName: 'TechVenture Solutions Ltd',
    amount: 15000000,
    currency: 'USD',
    interestRate: 4.75,
    maturityDate: '2027-06-30',
    originationDate: '2024-01-15',
    status: 'active',
    riskScore: 4.2,
    riskLevel: 'medium',
    industry: 'Technology',
    purpose: 'Acquisition financing and working capital',
    riskFactors: {
      credit: 4.0,
      market: 4.5,
      operational: 4.0,
      esg: 4.5,
    },
    covenants: [
      {
        id: 'COV-001-1',
        type: 'Debt Service Coverage Ratio',
        description: 'Minimum DSCR of 1.35x',
        threshold: 1.35,
        currentValue: 1.52,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-001-2',
        type: 'Leverage Ratio',
        description: 'Maximum Total Debt to EBITDA of 3.5x',
        threshold: 3.5,
        currentValue: 2.8,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-001-3',
        type: 'Interest Coverage Ratio',
        description: 'Minimum ICR of 3.0x',
        threshold: 3.0,
        currentValue: 3.8,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
    ],
    esgScore: {
      overall: 'B',
      environmental: 72,
      social: 68,
      governance: 81,
      notes: 'Strong corporate governance framework with improving environmental initiatives. Active diversity and inclusion programs.',
    },
    predictiveAnalytics: {
      defaultProbability30d: 0.02,
      defaultProbability60d: 0.04,
      defaultProbability90d: 0.06,
      covenantBreachRisk: [],
      recommendation: 'Maintain quarterly monitoring. Covenant headroom adequate. Consider rate review at next reset.',
    },
    lmaCompliance: {
      overallScore: 92,
      level: 'full',
      gaps: [],
      standardVersion: 'LMA 2023 Investment Grade',
      assessmentDate: new Date().toISOString(),
    },
  },
  {
    id: 'LOAN-2024-002',
    borrowerName: 'GreenEnergy Infrastructure Corp',
    amount: 50000000,
    currency: 'EUR',
    interestRate: 3.95,
    maturityDate: '2029-12-15',
    originationDate: '2024-03-01',
    status: 'active',
    riskScore: 2.8,
    riskLevel: 'low',
    industry: 'Renewable Energy',
    purpose: 'Solar farm construction and grid connection',
    riskFactors: {
      credit: 2.5,
      market: 3.0,
      operational: 2.8,
      esg: 2.5,
    },
    covenants: [
      {
        id: 'COV-002-1',
        type: 'Debt Service Coverage Ratio',
        description: 'Minimum DSCR of 1.25x',
        threshold: 1.25,
        currentValue: 1.68,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-002-2',
        type: 'Loan to Value',
        description: 'Maximum LTV of 75%',
        threshold: 75,
        currentValue: 62,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-002-3',
        type: 'Minimum Liquidity',
        description: 'Maintain minimum cash reserves of €5M',
        threshold: 5000000,
        currentValue: 7200000,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
    ],
    esgScore: {
      overall: 'A',
      environmental: 94,
      social: 78,
      governance: 85,
      notes: 'Exceptional environmental performance with certified renewable energy generation. Strong community engagement and transparent governance.',
    },
    predictiveAnalytics: {
      defaultProbability30d: 0.005,
      defaultProbability60d: 0.01,
      defaultProbability90d: 0.015,
      covenantBreachRisk: [],
      recommendation: 'Excellent credit profile. Consider green bond refinancing opportunities. No action required.',
    },
    lmaCompliance: {
      overallScore: 96,
      level: 'full',
      gaps: [],
      standardVersion: 'LMA 2023 Green Loan Principles',
      assessmentDate: new Date().toISOString(),
    },
  },
  {
    id: 'LOAN-2024-003',
    borrowerName: 'Urban Retail Holdings PLC',
    amount: 25000000,
    currency: 'GBP',
    interestRate: 6.25,
    maturityDate: '2026-09-30',
    originationDate: '2023-09-30',
    status: 'active',
    riskScore: 6.8,
    riskLevel: 'high',
    industry: 'Retail',
    purpose: 'Store portfolio expansion and digital transformation',
    riskFactors: {
      credit: 7.0,
      market: 7.5,
      operational: 6.0,
      esg: 6.5,
    },
    covenants: [
      {
        id: 'COV-003-1',
        type: 'Debt Service Coverage Ratio',
        description: 'Minimum DSCR of 1.15x',
        threshold: 1.15,
        currentValue: 1.18,
        status: 'at-risk',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-003-2',
        type: 'Fixed Charge Coverage',
        description: 'Minimum FCCR of 1.1x',
        threshold: 1.1,
        currentValue: 1.08,
        status: 'at-risk',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-003-3',
        type: 'Net Worth',
        description: 'Maintain minimum tangible net worth of £15M',
        threshold: 15000000,
        currentValue: 16500000,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
    ],
    esgScore: {
      overall: 'C',
      environmental: 52,
      social: 61,
      governance: 68,
      notes: 'Moderate ESG performance. Transitioning to sustainable supply chain practices. Governance improving under new management.',
    },
    predictiveAnalytics: {
      defaultProbability30d: 0.08,
      defaultProbability60d: 0.14,
      defaultProbability90d: 0.19,
      covenantBreachRisk: [
        {
          covenantId: 'COV-003-1',
          probability: 0.35,
          estimatedDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
        },
      ],
      recommendation: 'Enhanced monitoring required. Review covenant waivers. Consider restructuring discussions if Q3 performance deteriorates.',
    },
    lmaCompliance: {
      overallScore: 78,
      level: 'partial',
      gaps: [
        {
          section: 'Financial Covenants',
          issue: 'Covenant definitions deviate from LMA standard terminology',
          severity: 'medium',
        },
        {
          section: 'Reporting Requirements',
          issue: 'Monthly reporting frequency non-standard for facility type',
          severity: 'low',
        },
      ],
      standardVersion: 'LMA 2022 Leveraged',
      assessmentDate: new Date().toISOString(),
    },
  },
  {
    id: 'LOAN-2024-004',
    borrowerName: 'BioPharma Innovations SA',
    amount: 30000000,
    currency: 'CHF',
    interestRate: 4.15,
    maturityDate: '2028-03-31',
    originationDate: '2024-04-01',
    status: 'active',
    riskScore: 5.2,
    riskLevel: 'medium',
    industry: 'Pharmaceutical',
    purpose: 'R&D expansion and clinical trial funding',
    riskFactors: {
      credit: 5.5,
      market: 5.0,
      operational: 5.0,
      esg: 5.0,
    },
    covenants: [
      {
        id: 'COV-004-1',
        type: 'Debt to Equity Ratio',
        description: 'Maximum D/E ratio of 2.0x',
        threshold: 2.0,
        currentValue: 1.65,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-004-2',
        type: 'Current Ratio',
        description: 'Minimum current ratio of 1.5x',
        threshold: 1.5,
        currentValue: 1.72,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-004-3',
        type: 'Capital Expenditure',
        description: 'Maximum annual capex of CHF 12M without consent',
        threshold: 12000000,
        currentValue: 9800000,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
    ],
    esgScore: {
      overall: 'B',
      environmental: 71,
      social: 82,
      governance: 77,
      notes: 'Strong social impact through affordable medicine programs. Good environmental lab practices. Transparent clinical trial reporting.',
    },
    predictiveAnalytics: {
      defaultProbability30d: 0.03,
      defaultProbability60d: 0.05,
      defaultProbability90d: 0.08,
      covenantBreachRisk: [],
      recommendation: 'Monitor clinical trial progress and regulatory approvals. Adequate covenant cushion. Standard review cycle appropriate.',
    },
    lmaCompliance: {
      overallScore: 88,
      level: 'full',
      gaps: [],
      standardVersion: 'LMA 2023 Investment Grade',
      assessmentDate: new Date().toISOString(),
    },
  },
  {
    id: 'LOAN-2024-005',
    borrowerName: 'Atlantic Shipping Logistics Inc',
    amount: 42000000,
    currency: 'USD',
    interestRate: 5.85,
    maturityDate: '2027-11-15',
    originationDate: '2023-11-15',
    status: 'active',
    riskScore: 5.8,
    riskLevel: 'medium',
    industry: 'Transportation & Logistics',
    purpose: 'Fleet modernization and emission reduction program',
    riskFactors: {
      credit: 5.5,
      market: 6.5,
      operational: 5.5,
      esg: 5.5,
    },
    covenants: [
      {
        id: 'COV-005-1',
        type: 'Debt Service Coverage Ratio',
        description: 'Minimum DSCR of 1.3x',
        threshold: 1.3,
        currentValue: 1.42,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-005-2',
        type: 'Leverage Ratio',
        description: 'Maximum Total Debt to EBITDA of 4.0x',
        threshold: 4.0,
        currentValue: 3.6,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-005-3',
        type: 'Asset Coverage',
        description: 'Minimum collateral value of 125% of loan',
        threshold: 125,
        currentValue: 138,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
    ],
    esgScore: {
      overall: 'B',
      environmental: 75,
      social: 69,
      governance: 73,
      notes: 'Significant investment in fleet electrification and emission reduction. Good employee safety record. Transparent reporting practices.',
    },
    predictiveAnalytics: {
      defaultProbability30d: 0.04,
      defaultProbability60d: 0.07,
      defaultProbability90d: 0.10,
      covenantBreachRisk: [],
      recommendation: 'Monitor fuel price volatility impact. Fleet modernization on track. Maintain quarterly reviews given market sensitivity.',
    },
    lmaCompliance: {
      overallScore: 85,
      level: 'full',
      gaps: [],
      standardVersion: 'LMA 2023 Sustainability Linked',
      assessmentDate: new Date().toISOString(),
    },
    tradeListing: {
      id: 'TRADE-2024-001',
      loanId: 'LOAN-2024-005',
      sellerId: 'bank-xyz',
      sellerName: 'Global Credit Partners',
      askPrice: 41500000,
      currency: 'USD',
      minBidAmount: 39425000,
      listedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      expiryDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'listed',
      bids: [
        {
          id: 'BID-001',
          tradeId: 'TRADE-2024-001',
          bidderId: 'investor-abc',
          bidderName: 'Maritime Credit Fund',
          amount: 40200000,
          bidDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
          status: 'pending',
        },
      ],
      views: 47,
    },
  },
  {
    id: 'LOAN-2024-006',
    borrowerName: 'MetroProperty Development Group',
    amount: 68000000,
    currency: 'USD',
    interestRate: 5.45,
    maturityDate: '2029-06-30',
    originationDate: '2024-06-30',
    status: 'active',
    riskScore: 4.5,
    riskLevel: 'medium',
    industry: 'Real Estate',
    purpose: 'Mixed-use development project with affordable housing component',
    riskFactors: {
      credit: 4.5,
      market: 5.0,
      operational: 4.0,
      esg: 4.5,
    },
    covenants: [
      {
        id: 'COV-006-1',
        type: 'Loan to Cost',
        description: 'Maximum LTC of 70%',
        threshold: 70,
        currentValue: 65,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-006-2',
        type: 'Debt Yield',
        description: 'Minimum debt yield of 10%',
        threshold: 10,
        currentValue: 11.2,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-006-3',
        type: 'Pre-Leasing',
        description: 'Achieve 60% pre-leasing by completion',
        threshold: 60,
        currentValue: 48,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
    ],
    esgScore: {
      overall: 'A',
      environmental: 88,
      social: 91,
      governance: 79,
      notes: 'LEED Platinum certification target. 30% affordable housing allocation exceeds requirements. Strong community benefit agreements.',
    },
    predictiveAnalytics: {
      defaultProbability30d: 0.02,
      defaultProbability60d: 0.04,
      defaultProbability90d: 0.05,
      covenantBreachRisk: [],
      recommendation: 'Project on schedule and within budget. Pre-leasing progressing well. Monitor construction timeline for weather impacts.',
    },
    lmaCompliance: {
      overallScore: 91,
      level: 'full',
      gaps: [],
      standardVersion: 'LMA 2023 Real Estate Finance',
      assessmentDate: new Date().toISOString(),
    },
  },
  {
    id: 'LOAN-2024-007',
    borrowerName: 'AutoTech Manufacturing Ltd',
    amount: 22000000,
    currency: 'EUR',
    interestRate: 5.10,
    maturityDate: '2026-12-31',
    originationDate: '2024-01-01',
    status: 'active',
    riskScore: 5.5,
    riskLevel: 'medium',
    industry: 'Automotive',
    purpose: 'EV component production line and working capital',
    riskFactors: {
      credit: 5.5,
      market: 6.0,
      operational: 5.0,
      esg: 5.5,
    },
    covenants: [
      {
        id: 'COV-007-1',
        type: 'Debt Service Coverage Ratio',
        description: 'Minimum DSCR of 1.25x',
        threshold: 1.25,
        currentValue: 1.38,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-007-2',
        type: 'Working Capital',
        description: 'Maintain minimum working capital of €8M',
        threshold: 8000000,
        currentValue: 9200000,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-007-3',
        type: 'Leverage Ratio',
        description: 'Maximum Net Debt to EBITDA of 3.75x',
        threshold: 3.75,
        currentValue: 3.2,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
    ],
    esgScore: {
      overall: 'B',
      environmental: 76,
      social: 70,
      governance: 74,
      notes: 'Transitioning to sustainable manufacturing. Strong workforce training programs. Improving supply chain transparency.',
    },
    predictiveAnalytics: {
      defaultProbability30d: 0.03,
      defaultProbability60d: 0.06,
      defaultProbability90d: 0.09,
      covenantBreachRisk: [],
      recommendation: 'Monitor automotive sector headwinds. EV transition positioning positive. Maintain quarterly covenant monitoring.',
    },
    lmaCompliance: {
      overallScore: 87,
      level: 'full',
      gaps: [],
      standardVersion: 'LMA 2023 Investment Grade',
      assessmentDate: new Date().toISOString(),
    },
  },
  {
    id: 'LOAN-2024-008',
    borrowerName: 'DataCenter Systems Corp',
    amount: 95000000,
    currency: 'USD',
    interestRate: 4.50,
    maturityDate: '2030-08-31',
    originationDate: '2024-08-31',
    status: 'active',
    riskScore: 3.2,
    riskLevel: 'low',
    industry: 'Technology Infrastructure',
    purpose: 'Hyperscale data center construction with renewable power',
    riskFactors: {
      credit: 3.0,
      market: 3.5,
      operational: 3.0,
      esg: 3.5,
    },
    covenants: [
      {
        id: 'COV-008-1',
        type: 'Debt Service Coverage Ratio',
        description: 'Minimum DSCR of 1.4x',
        threshold: 1.4,
        currentValue: 1.78,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-008-2',
        type: 'Leverage Ratio',
        description: 'Maximum Total Debt to EBITDA of 5.0x',
        threshold: 5.0,
        currentValue: 3.8,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
      {
        id: 'COV-008-3',
        type: 'Occupancy Rate',
        description: 'Maintain minimum 85% contracted capacity',
        threshold: 85,
        currentValue: 92,
        status: 'compliant',
        lastChecked: new Date().toISOString(),
      },
    ],
    esgScore: {
      overall: 'A',
      environmental: 89,
      social: 74,
      governance: 86,
      notes: '100% renewable energy powered facility. Advanced cooling efficiency. Carbon neutral operations certified. Strong data privacy governance.',
    },
    predictiveAnalytics: {
      defaultProbability30d: 0.01,
      defaultProbability60d: 0.02,
      defaultProbability90d: 0.03,
      covenantBreachRisk: [],
      recommendation: 'Excellent credit quality. Strong demand fundamentals. Consider refinancing opportunities at lower rates.',
    },
    lmaCompliance: {
      overallScore: 94,
      level: 'full',
      gaps: [],
      standardVersion: 'LMA 2023 Green Loan Principles',
      assessmentDate: new Date().toISOString(),
    },
  },
]
